### ISSUE TITLE
Quick star doesn't appear at all

### ISSUE THREAD

**Issue by BuyMyMojo** [DiamondMiner88/BetterDiscordAddons#2]
There is no quick star button in the menu anymore.

**Comment by rushiiMachine** [comment]
not sure what to tell you since it still appears for me.
any related logs/errors?

**Comment by BuyMyMojo** [comment]
I don't know if this is related but when I right click on a message this appears in the logs

[log paste](https://paste.buymymojo.net/quserodekugoreco.log)

**Comment by rushiiMachine** [comment]
I cant see anything wrong with it
Was there an update recently that I didn't get?

**Comment by BuyMyMojo** [comment]
I'm on
```
Stable 136607 (7f224ff)
BetterDiscord 1.5.3
```

**Comment by rushiiMachine** [comment]
I'm on Stable 136806 so please update and see if that fixes the issue

**Comment by BuyMyMojo** [comment]
I have updated to `Stable 137095 (fb67ae9)` and toggled every plugin I have installed off except for quick star and nothing changed.
I enabled quick star and the common library plugins to be safe and still nothing.
I refreshed between each change to be safe.

**Comment by rushiiMachine** [comment]
cant reproduce then
